//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMuteUs_Portable.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoMuteUs_Portable.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseEnvPathWindow_CancelBtn {
            get {
                return ResourceManager.GetString("ChooseEnvPathWindow_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnvPath is required to set properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseEnvPathWindow_EnvPath_RequiredToFill {
            get {
                return ResourceManager.GetString("ChooseEnvPathWindow_EnvPath_RequiredToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseEnvPathWindow_SaveBtn {
            get {
                return ResourceManager.GetString("ChooseEnvPathWindow_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChooseEnvPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseEnvPathWindow_Title {
            get {
                return ResourceManager.GetString("ChooseEnvPathWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   automuteus.exe successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Automuteus_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Automuteus_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   automuteus.exe has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Automuteus_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Automuteus_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   auto restarted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_AutoRestarted {
            get {
                return ResourceManager.GetString("MainLogger_AutoRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update of AutoMuteUs Portable detected: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_CheckUpdate_UpdateDetected {
            get {
                return ResourceManager.GetString("MainLogger_CheckUpdate_UpdateDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .env successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_EnvFile_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_EnvFile_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_EnvFile_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_EnvFile_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to move EnvPath: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_EnvPathChange_FailToMoveEnvPath {
            get {
                return ResourceManager.GetString("MainLogger_EnvPathChange_FailToMoveEnvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load binaries: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_FailToLoadBinary {
            get {
                return ResourceManager.GetString("MainLogger_FailToLoadBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   galactus.exe successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Galactus_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Galactus_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   galactus.exe has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Galactus_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Galactus_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get refs/tags. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_HttpClientRequestFailed {
            get {
                return ResourceManager.GetString("MainLogger_HttpClientRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File .env saved in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_LoadBinaries_EnvFileSaved {
            get {
                return ResourceManager.GetString("MainLogger_LoadBinaries_EnvFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_LoadBinaries_FailToCreateDirectory {
            get {
                return ResourceManager.GetString("MainLogger_LoadBinaries_FailToCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   diffenvs.json successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_LoadDiffEnvs_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_LoadDiffEnvs_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_LoadDiffEnvs_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_LoadDiffEnvs_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log output started: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_LogOutputStarted {
            get {
                return ResourceManager.GetString("MainLogger_LogOutputStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created database named: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_DatabaseCreated {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_DatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renamed the database to: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_DatabaseRenamed {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_DatabaseRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to initialize Postgres database properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_FailToInitialize {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_FailToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres password didn&apos;t set properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_FailToRenamePass {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_FailToRenamePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres user name didn&apos;t set properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_FailToRenameUser {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_FailToRenameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to setup Postgres: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_FailToSetup {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_FailToSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully initialized Postgres database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_InitializedSuccessfully {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_InitializedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_InitializeManually {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_InitializeManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres&apos; binary successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres user name successfully set to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_RenamedUserSuccessfully {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_RenamedUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating Postgres user name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_RenameUser {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_RenameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   postgres.sql successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_SQLFile_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_SQLFile_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   postgres.sql has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_SQLFile_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_SQLFile_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   postgres.zip has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing Postgres server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_StartInitialize_1 {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_StartInitialize#1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing Postgres database using postgres.sql に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_StartInitialize_2 {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_StartInitialize#2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres started to setup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_StartSetup {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_StartSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set it manually. Current user name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_TryRenameUserManually {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_TryRenameUserManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set it manually. Current password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_TryUpdatePasswordManually {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_TryUpdatePasswordManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postgres password successfully set to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_UpdatedPasswordSuccessfully {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_UpdatedPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating Postgres pass: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_UpdatePass {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_UpdatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created user named: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Postgres_UserCreated {
            get {
                return ResourceManager.GetString("MainLogger_Postgres_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   postgres closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_PostgresClosed {
            get {
                return ResourceManager.GetString("MainLogger_PostgresClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to close postgres. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_PostgresFailedToClose {
            get {
                return ResourceManager.GetString("MainLogger_PostgresFailedToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_ProcessStarted {
            get {
                return ResourceManager.GetString("MainLogger_ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redis&apos; binary successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Redis_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Redis_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   redis.zip has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Redis_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Redis_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   redis-cli.exe successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RedisCli_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_RedisCli_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   redis-cli.exe has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RedisCli_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_RedisCli_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to close redis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RedisFailToClose {
            get {
                return ResourceManager.GetString("MainLogger_RedisFailToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To host AutoMuteUs again, please relaunch AutoMuteUs Portable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RelaunchApp {
            get {
                return ResourceManager.GetString("MainLogger_RelaunchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to download Recommended Version Combination. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RVC_DownloadFailed {
            get {
                return ResourceManager.GetString("MainLogger_RVC_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommended Version Combination has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RVC_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_RVC_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to download hash of Recommended Version Combination. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RVCHash_DownloadFailed {
            get {
                return ResourceManager.GetString("MainLogger_RVCHash_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash of Recommended Version Combination has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RVCHash_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_RVCHash_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update of Recommended Version Combination detected: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_RVCHash_UpdateDetected {
            get {
                return ResourceManager.GetString("MainLogger_RVCHash_UpdateDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to close manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_TryCloseManually {
            get {
                return ResourceManager.GetString("MainLogger_TryCloseManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Version {
            get {
                return ResourceManager.GetString("MainLogger_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wingman.exe successfully loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Wingman_Loaded {
            get {
                return ResourceManager.GetString("MainLogger_Wingman_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wingman.exe has been downloading. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainLogger_Wingman_StartDownload {
            get {
                return ResourceManager.GetString("MainLogger_Wingman_StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There&apos;s newer version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_CheckUpdate_UpdateDetected_Text_1 {
            get {
                return ResourceManager.GetString("MainWindow_CheckUpdate_UpdateDetected_Text#1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you wanna check it out on Github? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_CheckUpdate_UpdateDetected_Text_2 {
            get {
                return ResourceManager.GetString("MainWindow_CheckUpdate_UpdateDetected_Text#2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_CheckUpdate_UpdateDetected_Title {
            get {
                return ResourceManager.GetString("MainWindow_CheckUpdate_UpdateDetected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DetailedLogging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_DetailedLogLabel {
            get {
                return ResourceManager.GetString("MainWindow_DetailedLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXPORT LOG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ExportLogBtn {
            get {
                return ResourceManager.GetString("MainWindow_ExportLogBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To export current log, application will close the server.
        ///Are you sure to proceed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ExportLogBtn_Caution_Text {
            get {
                return ResourceManager.GetString("MainWindow_ExportLogBtn_Caution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ExportLogBtn_Caution_Title {
            get {
                return ResourceManager.GetString("MainWindow_ExportLogBtn_Caution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully put log into current executable directory: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ExportLogBtn_Result_Text {
            get {
                return ResourceManager.GetString("MainWindow_ExportLogBtn_Result_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ExportLogBtn_Result_Title {
            get {
                return ResourceManager.GetString("MainWindow_ExportLogBtn_Result_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MainLogging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_MainLogLabel {
            get {
                return ResourceManager.GetString("MainWindow_MainLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_ResetBtn {
            get {
                return ResourceManager.GetString("MainWindow_ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommended Version Combination has been updated.
        ///Check it on Settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_RVCUpdate_Text {
            get {
                return ResourceManager.GetString("MainWindow_RVCUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommended Version Combination update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_RVCUpdate_Title {
            get {
                return ResourceManager.GetString("MainWindow_RVCUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To change settings, application will close the server.
        ///Are you sure to proceed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_1_Text {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_1_Title {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not close the app until new message box be shown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_2_Text {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_2_Title {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To host AutoMuteUs again, please relaunch AutoMuteUs Portable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_3_Text {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_SettingsBtn_Caution_3_Title {
            get {
                return ResourceManager.GetString("MainWindow_SettingsBtn_Caution#3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation requires restarting application.
        ///Are you sure to do? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_DeleteAllBinaries_RequireRestart_Text {
            get {
                return ResourceManager.GetString("ResetWindow_DeleteAllBinaries_RequireRestart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE ALL BINARIES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_DeleteAllBinaries_RequireRestart_Title {
            get {
                return ResourceManager.GetString("ResetWindow_DeleteAllBinaries_RequireRestart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE ALL BINARIES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_DeleteAllBinariesBtn {
            get {
                return ResourceManager.GetString("ResetWindow_DeleteAllBinariesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation requires restarting application.
        ///Are you sure to do? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_ResetAllProperties_RequireRestart_Text {
            get {
                return ResourceManager.GetString("ResetWindow_ResetAllProperties_RequireRestart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET ALL PROPERTIES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_ResetAllProperties_RequireRestart_Title {
            get {
                return ResourceManager.GetString("ResetWindow_ResetAllProperties_RequireRestart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET ALL PROPERTIES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_ResetAllPropertiesBtn {
            get {
                return ResourceManager.GetString("ResetWindow_ResetAllPropertiesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After you close this window, application will close.
        ///Please start the application manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_RestartCaution_Text {
            get {
                return ResourceManager.GetString("ResetWindow_RestartCaution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESTART CAUTION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_RestartCaution_Title {
            get {
                return ResourceManager.GetString("ResetWindow_RestartCaution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetWindow_Title {
            get {
                return ResourceManager.GetString("ResetWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to move EnvPath: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_EnvPathChange_FailToMoveEnvPath_Text {
            get {
                return ResourceManager.GetString("Settings_EnvPathChange_FailToMoveEnvPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_CancelBtn {
            get {
                return ResourceManager.GetString("SettingsWindow_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_ChangeEnvPathBtn {
            get {
                return ResourceManager.GetString("SettingsWindow_ChangeEnvPathBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_SaveBtn {
            get {
                return ResourceManager.GetString("SettingsWindow_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is set as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateEnvVars_PostgresPass_AutoGenerated_Text {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateEnvVars_PostgresPass_AutoGenerated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PASSWORD GENERATOR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateEnvVars_PostgresPass_AutoGenerated_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateEnvVars_PostgresPass_AutoGenerated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is required to fill. Do you want to use auto generated password? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateEnvVars_PostgresPass_RequiredToFill_Text {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateEnvVars_PostgresPass_RequiredToFill_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PASSWORD GENERATOR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateEnvVars_PostgresPass_RequiredToFill_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateEnvVars_PostgresPass_RequiredToFill_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is required to fill.
        ///Fill it and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateEnvVars_RequiredToFill_Text {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateEnvVars_RequiredToFill_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is required to fill.
        ///Fill it and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UpdateUserVars_RequiredToFill_Text {
            get {
                return ResourceManager.GetString("SettingsWindow_UpdateUserVars_RequiredToFill_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Recommended Version Combination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindow_UseRVCBtn {
            get {
                return ResourceManager.GetString("SettingsWindow_UseRVCBtn", resourceCulture);
            }
        }
    }
}
